---
# tasks file for ansible-infra/roles/nodejs
- name: Installing nodejs
  apt: name=nodejs state=present

- name: Installing npm
  apt: name=npm state=present

- name: Installing nodejs legacy
  apt: name=nodejs-legacy state=present
